django_auth_example/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'users/', include('users.urls')),
    path(r'users/', include('django.contrib.auth.urls')),
    path(r'$/', views.index, name='base'),
    path(r'article/', include('article.urls')),
    path(r'question/', include('question.urls')),
]

question/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'question'  # 一定要写这一行，否则html中会报错 'article' is not a registered namespace

urlpatterns = [
    path(r'question_post/', views.question_post, name='question_post'),
    path(r'question_list/', views.question_list, name='question_list'),
    path(r'question_detail/<int:id>/', views.question_detail, name='question_detail'),
    path(r'question_search/', views.question_search, name='question_search'),
    path(r'question_myquestion/', views.question_myquestion, name='question_myquestion'),
    path(r'question_mysearch/', views.question_mysearch, name='question_mysearch'),
    path(r'question_delete/<int:id>/', views.question_delete, name='question_delete'),
    path(r'question_change/<int:id>/', views.question_change, name='question_change'),
    path(r'question_othersquestion/<int:id>/', views.question_othersquestion, name='question_othersquestion'),
    path(r'question_othersearch/<int:id>/', views.question_othersearch, name='question_othersearch'),
    path(r'question_collect/<int:id>/', views.question_collect, name='question_collect'),
    path(r'question_collect_cancel/<int:id>/', views.question_collect_cancel, name='question_collect_cancel'),
    path(r'question_report/<int:id>/', views.question_report, name='question_report'),
    path(r'answer_report/<int:id>/', views.answer_report, name='answer_report'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path(r'register/', views.register, name='register'),
    path(r'user_info/', views.user_info, name='user_info'),
    path(r'user_info_edit/', views.myself_edit, name='user_info_edit'),
    path(r'upload_image/', views.my_image, name='upload_image'),
    path(r'others_info/<int:id>/', views.others_info, name='others_info'),
    path(r'follow_on/<int:id>/', views.follow_on, name='follow_on'),
    path(r'follow_cancel/<int:id>/', views.follow_cancel, name='follow_cancel'),
    path(r'user_follow/', views.user_follow, name='user_follow'),
    path(r'user_fan/', views.user_fan, name='user_fan'),
    path(r'my_collect/', views.my_collect, name='my_collect'),
]

article/models.py
from django.db import models

# Create your models here.

from django.db import models
from users.models import User
from django.utils import timezone
from django.urls import reverse


class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="article", null=True)
    title = models.CharField(max_length=200)
    content = models.TextField(null=True)
    created = models.DateTimeField(default=timezone.now, null=True)
    updated = models.DateTimeField(auto_now=True, null=True)
    users_like = models.ManyToManyField(User, related_name="articles_like", blank=True)
    collect_user = models.ManyToManyField(User, related_name="collect_user", blank=True)
    total_views = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ("-updated",)

    # 对数据库中的这两个字段建立索引，以后就可以通过每篇文章的id和slug来获取该文章对象了，
    # 这样建立索引以后，能提高读取文章对象的速度。
    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="comments")
    commentator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="commentator", null=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return "{0} 在 {1}博客中评论了".format(self.commentator.username, self.article)


class Report_Article(models.Model):
    reporter = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reporter_article")
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="reported_article")
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{0} 举报了 {1}博客，原因是：{2}.时间是{3}".format(self.reporter.username, self.article.title, self.content,
                                                     self.created)


class Report_Commit(models.Model):
    reporter = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reporter_commit")
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name="reported_commit")
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{0} 举报了 {1}用户在标题为{2}的博客下的{3}的评论，原因是：{4}。时间是{5}".format(self.reporter.username,
                                                                       self.comment.commentator.username,
                                                                       self.comment.article.title, self.comment.body,
                                                                       self.content, self.created)

question/models.py
from django.db import models
from users.models import User
from django.utils import timezone


# Create your models here.

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="question", null=True)
    title = models.CharField(max_length=200, null=True)
    content = models.TextField(null=True)
    created = models.DateTimeField(default=timezone.now, null=True)
    integral = models.IntegerField(default=0)
    collect_user = models.ManyToManyField(User, related_name="collect_user_question", blank=True)

    class Meta:
        ordering = ("-created",)

    # 返回的是个必填的字段即null=False
    # 返回的即是admin后台管理里面显示的内容
    def __str__(self):
        return self.content


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="answers")
    answertor = models.ForeignKey(User, on_delete=models.CASCADE, related_name="answertor", null=True)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return "Comment by {0} on {1}".format(self.answertor.username, self.question)


class Report_Question(models.Model):
    reporter = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reporter_question")
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="reported_question")
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{0} 举报了 {1}问答，原因是：{2}.时间是：{3}".format(self.reporter.username, self.question.title, self.content,
                                                      self.created)


class Report_Answer(models.Model):
    reporter = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reporter_answer")
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name="reported_answer")
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{0} 举报了 {1}用户在标题为{2}的问答下的{3}的回答，原因是：{4},时间是{5}".format(self.reporter.username,
                                                                       self.answer.answertor.username,
                                                                       self.answer.question.title, self.answer.content,
                                                                       self.content, self.created)

question/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Question, Answer, Report_Question,Report_Answer
from users.models import User
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.db.models import Q


# Create your views here.

def question_list(request):
    questions = Question.objects.all()
    return render(request, 'question/question_list.html', {'questions': questions})


@login_required(login_url='/users/login/')
def question_post(request):
    user = User.objects.get(username=request.user.username)
    if request.method == "POST":
        content = request.POST.get('content', None)
        integral = request.POST.get('integral', None)
        title = request.POST.get('title', None)
        # article_id = request.POST.get('article_id', None)
        new_question = Question()
        new_question.content = content
        new_question.author = user
        new_question.title = title
        new_question.integral = integral
        new_question.save()
        return redirect('question:question_list')
    else:
        pass
    return render(request, 'question/question_post.html')


@login_required(login_url='/users/login/')
def question_detail(request, id):
    question = Question.objects.get(id=id)
    user = User.objects.get(username=request.user.username)
    a = Question.objects.filter(id=id, collect_user=user)
    if request.method == "POST":
        pass
        content = request.POST.get('content', None)
        new_answer = Answer()
        new_answer.question = question
        new_answer.content = content
        new_answer.answertor = user
        new_answer.save()
    else:
        pass
    return render(request, 'question/question_detail.html', {'question': question, 'user': user, 'a': a})


def question_search(request):
    search = request.GET.get('search', None)
    error_msg = ''
    if search:
        questions = Question.objects.filter(Q(title__icontains=search) | Q(content__icontains=search))
    else:
        # 将 search 参数重置为空,否则search则为None
        search = ''
        questions = Question.objects.all()
    return render(request, 'question/question_search.html', {'questions': questions})


@login_required(login_url='/users/login/')
def question_myquestion(request):
    user = User.objects.get(username=request.user.username)
    questions = Question.objects.filter(author=user)
    return render(request, 'question/question_myquestion.html', {'questions': questions})


@login_required(login_url='/users/login/')
def question_mysearch(request):
    search = request.GET.get('search', None)
    user = User.objects.get(username=request.user.username)
    error_msg = ''
    if search:
        questions = Question.objects.filter((Q(title__icontains=search) | Q(content__icontains=search)), author=user)
    else:
        # 将 search 参数重置为空,否则search则为None
        search = ''
        questions = Question.objects.filter(author=user)
    return render(request, 'question/question_mysearch.html', {'questions': questions})


@login_required(login_url='/users/login/')
def question_delete(request, id):
    # 根据 id 获取需要删除的文章
    question = Question.objects.get(id=id)
    # 调用.delete()方法删除文章
    question.delete()
    # 完成删除后返回文章列表
    return redirect("question:question_list")


@login_required(login_url='/users/login/')
@csrf_exempt
def question_change(request, id):
    user = User.objects.get(username=request.user.username)
    question = Question.objects.get(id=id)
    if request.method == "POST":
        title = request.POST.get('title', None)
        content = request.POST.get('content', None)
        integral = request.POST.get('integral', None)
        question.title = title
        question.content = content
        question.integral = integral
        question.save()
        return redirect('question:question_detail', id)
    else:
        return render(request, "question/question_change.html", {"question": question})


def question_othersquestion(request, id):
    user = User.objects.get(id=id)
    questions = Question.objects.filter(author=user)
    return render(request, 'question/question_othersquestion.html', {'questions': questions, 'user': user})


def question_othersearch(request, id):
    search = request.GET.get('search', None)
    user = User.objects.get(id=id)
    error_msg = ''
    if search:
        questions = Question.objects.filter((Q(title__icontains=search) | Q(content__icontains=search)), author=user)
    else:
        # 将 search 参数重置为空,否则search则为None
        search = ''
        questions = Question.objects.filter(author=user)
    return render(request, 'question/question_othersearch.html', {'questions': questions, 'user': user})


@login_required(login_url='/users/login/')
def question_collect(request, id):
    # 根据 id 获取需要收藏的文章
    question = Question.objects.get(id=id)
    user = User.objects.get(username=request.user.username)
    # 多对多关系赋值时用add而不是=
    question.collect_user.add(user)
    question.save()
    # 完成收藏后返回文章详情
    a = Question.objects.filter(id=id, collect_user=user)
    return render(request, 'question/question_detail.html', {'question': question, 'user': user, 'a': a})


@login_required(login_url='/users/login/')
def question_collect_cancel(request, id):
    # 根据 id 获取需要取消收藏的文章
    question = Question.objects.get(id=id)
    user = User.objects.get(username=request.user.username)
    # 多对多关系消除时用remove而不是赋值为None或者remove（）
    question.collect_user.remove(user)
    question.save()
    a = Question.objects.filter(id=id, collect_user=user)
    # 完成收藏后返回文章详情
    return render(request, 'question/question_detail.html', {'question': question, 'user': user, 'a': a})


@login_required(login_url='/users/login/')
@csrf_exempt
def question_report(request, id):
    user = User.objects.get(username=request.user.username)
    question = Question.objects.get(id=id)
    if request.method == "POST":
        content = request.POST.get('content', None)
        ra = Report_Question()
        ra.reporter = user
        ra.question = question
        ra.content = content
        ra.save()
        return render(request, 'report_success.html')
    else:
        return render(request, 'question/question_report.html', {'question': question})


@login_required(login_url='/users/login/')
@csrf_exempt
def answer_report(request, id):
    # 传进来的id是回答的id
    answer = Answer.objects.get(id=id)
    user = User.objects.get(username=request.user.username)
    if request.method == "POST":
        content = request.POST.get('content', None)
        ra = Report_Answer()
        ra.reporter = user
        ra.answer = answer
        ra.content = content
        ra.save()
        return render(request, 'report_success.html')
    else:
        return render(request, 'question/answer_report.html', {'answer': answer})

templates/question/answer_report.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}举报回答{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
{% endblock %}

<div class="main">
    {% block main %}
        <h3 class="page-title">举报回答</h3>
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-container">
                <div class="form-group">
                    <p>您要举报用户:{{ answer.answertor.username }}
                        博客标题:{{ answer.question.title }}
                        评论内容：{{ answer.content }}
                    </p>
                </div>
                <div class="form-group">
                    <textarea class="form-control" rows="7" placeholder="请输入举报原因（越详细越好）" name="content"></textarea>
                </div>
                <div class="form_button">
                    <button type="submit" class="btn btn-primary">举报</button>
                </div>
            </div>
        </form>
        <style>
            .form-container {
                width: 800px;
                margin: 0 auto;
                text-align: left;
            }

            .page-title {
                text-align: center;
            }

            body {
                background: #E6E6E6;
            }

            .main {
                background: #fff;
                width: 1000px;
                margin: 0 auto;
                overflow: hidden;
                padding: 10px;
            }

            .form_button {
                float: right;
            }
        </style>

        <script type="text/javascript" src='{% static "js/jquery-1.11.1.min.js" %}'></script>
        <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
    {% endblock %}
</div>

templates/question/question_change.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}修改问答{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
{% endblock %}

<div class="main">
    {% block main %}
        <h3 class="page-title">发布问答</h3>
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-container">
                <div class="form-group">
                    <p class="position_title">标题:</p>
                    <input class="form-control" type="text" placeholder="" name="title" value="{{ question.title }}">
                </div>
                <div class="form-group">
                    <p class="position_integral">赏金(整数):</p>
                    <input class="form-control" type="text" placeholder="" name="integral" value="{{ question.integral }}">
                </div>
                <div class="form-group">
                    <p class="position_content">内容:</p>
                    <textarea class="form-control" rows="7" placeholder="" name="content">{{ question.content }}</textarea>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">提交修改</button>
                </div>
            </div>
        </form>
        <style>
            .form-container {
                width: 800px;
                margin: 0 auto;
                text-align: right;
            }
            .position_title{
                text-align: left;
            }
            .position_content{
                text-align: left;
            }
            .position_integral{
                text-align: left;
            }

            .page-title {
                text-align: center;
            }

            body {
                background: #E6E6E6;
            }

            .main {
                background: #fff;
                width: 1000px;
                margin: 0 auto;
                overflow: hidden;
                padding: 10px;
            }
        </style>

        <script type="text/javascript" src='{% static "js/jquery-1.11.1.min.js" %}'></script>
        <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
        <script type="text/javascript">
            function publish_article() {
                {#var title = $("#id_title").val();#}
                {#var body = $("#id_body").val();#}
                {#var article_tags = [];#}
                {#$.each($("input[name='article_tag']:checked"), function () {#}
                {#    article_tags.push($(this).val());});#}
                {#"tags": JSON.stringify(article_tags)#}
                $.ajax({
                    url: "{% url 'question:question_post' %}",
                    dataType: "text",
                    type: "GET",
                    {#data: {"title": title, },#}
                    success: function (e) {
                        if (e == "1") {
                            layer.msg("发布成功！", {
                                time: 700,
                                end: function () {
                                    location.href = "{% url 'question:question_list' %}";//修改后：文章发布成功后跳转到文章列表
                                }
                            });
                        } else if (e == "2") {
                            layer.msg("发布失败，请重试！", {
                                time: 700,
                                end: function () {
                                }
                            });
                        }
                    },
                });
            }
        </script>
        <script type="text/javascript" src='{% static "editor/editormd.min.js" %}'></script>
        <script type="text/javascript">
            $(function () {
                var editor = editormd("editormd", {
                    width: "100%",
                    height: 640,
                    syncScrolling: "single",
                    path: "{% static 'editor/lib/' %}"
                });
            });
        </script>
    {% endblock %}
</div>

templates/question/question_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}文章详情{% endblock %}

{% block head %}

{% endblock %}

<div class="main">
    {% block main %}
        {% with total_likes=article.users_like.count users_like=article.users_like.all %}
            <h3 class="page-title">{{ question.title }}</h3>
            <p class="question-info">
                <span class="span">提问者:
                    {% if question.author.photo %}
                        <a href="{% url 'users:others_info' question.author.id %}">
                        <img src="{{ question.author.photo | striptags }}" class="img-circle" id="my_photo" width="20px"
                             name="user_face">
                        </a>
                    {% else %}
                        <a href="{% url 'users:others_info' question.author.id %}">
                        <img name="user_face" src="{% static 'images/user.jpg' %}" class="img-circle" id="my_photo"
                             width="20px">
                        </a>
                    {% endif %}
                    <a href="{% url 'users:others_info' question.author.id %}">{{ question.author.username }}</a>
                </span>
                <span>提问时间:{{ question.created }}</span>
                <span>赏金:{{ question.integral }}积分</span>
                {% if question.author.username != user.username %}
                    {% if a.exists %}
                        <a href="#" onclick="confirm_collect_cancel()">取消收藏</a>
                    {% else %}
                        <a href="#" onclick="confirm_collect()">收藏问答</a>
                    {% endif %}
                {% endif %}
                {% if question.author.username == user.username %}
                    <a href="#" onclick="confirm_delete()">删除问答</a>
                {% endif %}
                {% if question.author.username == user.username %}
                    <a href="{% url 'question:question_change' question.id %}">修改问答</a>
                {% endif %}
            </p>


            <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}"/>
            <div id='editormd-view'>
        <textarea id="append-test" style="display:none;" class="question-content">
{{ question.content }}
        </textarea>
            </div>
            <br>
            <hr>
            <h3><span class="glyphicon glyphicon-bullhorn"></span>本文有
                {{ question.answers.count }}
                条回答
            </h3>

            {% for answer in question.answers.all %}
                <div>
                    <p><strong>
                        {% if answer.answertor.photo %}
                            <a href="{% url 'users:others_info' answer.answertor.id %}">
                                <img src="{{ answer.answertor.photo | striptags }}" class="img-circle" id="my_photo"
                                     width="20px"
                                     name="user_face">
                            </a>
                        {% else %}
                            <a href="{% url 'users:others_info' answer.answertor.id %}">
                                <img name="user_face" src="{% static 'images/user.jpg' %}" class="img-circle"
                                     id="my_photo"
                                     width="20px">
                            </a>
                        {% endif %}
                        <a href="{% url 'users:others_info' answer.answertor.id %}">{{ answer.answertor }}</a>
                    </strong>回答:</p>
                    <p style="margin-left:40px;">{{ answer.content }}</p>
                    <a href="{% url 'question:answer_report' answer.id %}" style="color:#BBBBBB;float:right">举报</a>
            {% empty %}
                <div class="question-group">
                    还没有回答哦，快来回答问题吧！
                </div>
            {% endfor %}
            <hr>
            <form action="." method="post">
                {% csrf_token %}
                <div class="form-group">
                    <textarea type="text" name="content" class="form-control" placeholder="请填写你的回答"></textarea>
                </div>
                <input type="hidden" name="article_id" value="{{ question.id }}">
                <div class="form-group" style="text-align: right">
                    <button class="btn btn-primary">立即回答</button>
                </div>
            </form>
            <a href="#" onclick="report_question()">举报</a>
            </div>


            <script src='{% static "js/jquery-1.11.1.min.js" %}'></script>
            <script src='{% static "editor/lib/marked.min.js" %}'></script>
            <script src='{% static "editor/lib/prettify.min.js" %}'></script>
            <script src='{% static "editor/lib/raphael.min.js" %}'></script>
            <script src='{% static "editor/lib/underscore.min.js" %}'></script>
            <script src='{% static "editor/lib/sequence-diagram.min.js" %}'></script>
            <script src='{% static "editor/lib/flowchart.min.js" %}'></script>
            <script src='{% static "editor/lib/jquery.flowchart.min.js" %}'></script>
            <script src='{% static "editor/editormd.js" %}'></script>
            <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
            <script type="text/javascript">
                $(function () {
                    editormd.markdownToHTML("editormd-view", {
                        htmlDecode: "style, script, iframe",
                        emoji: true,
                        taskList: true,
                        tex: true,
                        flowChart: true,
                        sequenceDiagram: true,
                    });
                });

            </script>


            <script>
                // 删除文章的函数
                function confirm_delete() {
                    // 调用layer弹窗组件
                    layer.open({
                        // 弹窗标题
                        title: "确认删除",
                        // 正文
                        content: "确认删除这篇问答吗？",
                        // 点击确定按钮后调用的回调函数
                        yes: function (index, layero) {
                            // 指定应当前往的 url
                            location.href = '{% url "question:question_delete" question.id %}'
                        },
                    })
                }
            </script>
            <script>
                // 收藏文章的函数
                function confirm_collect() {
                    // 调用layer弹窗组件
                    layer.open({
                        // 弹窗标题
                        title: "确认收藏",
                        // 正文
                        content: "确认收藏这篇问答吗？",
                        // 点击确定按钮后调用的回调函数
                        yes: function (index, layero) {
                            // 指定应当前往的 url
                            location.href = '{% url "question:question_collect" question.id %}'
                        },
                    })
                }
            </script>
            <script>
                // 收藏文章的函数
                function confirm_collect_cancel() {
                    // 调用layer弹窗组件
                    layer.open({
                        // 弹窗标题
                        title: "取消收藏",
                        // 正文
                        content: "确认取消收藏这篇问答吗？",
                        // 点击确定按钮后调用的回调函数
                        yes: function (index, layero) {
                            // 指定应当前往的 url
                            location.href = '{% url "question:question_collect_cancel" question.id %}'
                        },
                    })
                }
            </script>
            <script>
                // 举报博客的函数
                function report_question() {
                    // 调用layer弹窗组件
                    layer.open({
                        // 弹窗标题
                        title: "举报问答",
                        // 正文
                        content: "确认举报这篇问答吗？举报属实会有奖励，但举报若不属实则会有惩罚",
                        // 点击确定按钮后调用的回调函数
                        yes: function (index, layero) {
                            // 指定应当前往的 url
                            location.href = '{% url "question:question_report" question.id %}'
                        },
                    })
                }
            </script>
            <style>
                .main {
                    background: #fff;
                    width: 750px;
                    margin: 0 auto;
                    overflow: hidden;
                    padding: 10px;
                }

                .page-title {
                    text-align: center;
                    font-weight: 800;
                }

                .question-info {
                    text-align: center;
                    margin-top: 20px;

                }

                .question-content {
                    margin-left: 10px;
                }

                .span {
                    margin-right: 10px;
                }

                .form-control {
                    width: 650px;

                }

                .form-group {
                    margin-left: 10px;
                }

                .font-control {
                    margin-left: 10px;
                }

                .form-group {
                    margin-right: 48px;
                }

                .line-control {
                    line-height: 300%;
                }

                .answer-list li {
                    list-style: none;
                    border-bottom: 1px solid #eee;
                    padding-top: 10px;
                }

                .answer-list {
                    padding-left: 0;
                }

                .user-info {
                    font-size: 16px;
                    color: #9b9b9b;
                    line-height: 40px;
                }

                .user-info .username {
                    margin-left: 20px;
                }

                .user-info .create-time {
                    float: right;
                }

                .answer-content {
                    margin-left: 60px;
                    font-size: 20px;
                }
            </style>
        {% endwith %}
    {% endblock %}
</div>