article/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'article'  # 一定要写这一行，否则html中会报错 'article' is not a registered namespace

urlpatterns = [
    path(r'article_post/', views.article_post, name='article_post'),
    path(r'article_list/', views.article_list, name='article_list'),
    path(r'article_detail/<int:id>/', views.article_detail, name='article_detail'),
    path(r'like_article/', views.like_article, name='like_article'),
    path(r'article_search/', views.article_search, name='article_search'),
    path(r'article_myblog/', views.article_myblog, name='article_myblog'),
    path(r'article_mysearch/', views.article_mysearch, name='article_mysearch'),
    path(r'article_delete/<int:id>/', views.article_delete, name='article_delete'),
    path(r'article_collect/<int:id>/', views.article_collect, name='article_collect'),
    path(r'article_collect_cancel/<int:id>/', views.article_collect_cancel, name='article_collect_cancel'),
    path(r'article_change/<int:id>/', views.article_change, name='article_change'),
    path(r'article_othersblog/<int:id>/', views.article_othersblog, name='article_othersblog'),
    path(r'article_othersearch/<int:id>/', views.article_othersearch, name='article_othersearch'),
    path(r'article_report/<int:id>/', views.article_report, name='article_report'),
    path(r'comment_report/<int:id>/', views.comment_report, name='comment_report'),
]

django_auth_example/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'users/', include('users.urls')),
    path(r'users/', include('django.contrib.auth.urls')),
    path(r'$/', views.index, name='base'),
    path(r'article/', include('article.urls')),
    path(r'question/', include('question.urls')),
]

question/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'question'  # 一定要写这一行，否则html中会报错 'article' is not a registered namespace

urlpatterns = [
    path(r'question_post/', views.question_post, name='question_post'),
    path(r'question_list/', views.question_list, name='question_list'),
    path(r'question_detail/<int:id>/', views.question_detail, name='question_detail'),
    path(r'question_search/', views.question_search, name='question_search'),
    path(r'question_myquestion/', views.question_myquestion, name='question_myquestion'),
    path(r'question_mysearch/', views.question_mysearch, name='question_mysearch'),
    path(r'question_delete/<int:id>/', views.question_delete, name='question_delete'),
    path(r'question_change/<int:id>/', views.question_change, name='question_change'),
    path(r'question_othersquestion/<int:id>/', views.question_othersquestion, name='question_othersquestion'),
    path(r'question_othersearch/<int:id>/', views.question_othersearch, name='question_othersearch'),
    path(r'question_collect/<int:id>/', views.question_collect, name='question_collect'),
    path(r'question_collect_cancel/<int:id>/', views.question_collect_cancel, name='question_collect_cancel'),
    path(r'question_report/<int:id>/', views.question_report, name='question_report'),
    path(r'answer_report/<int:id>/', views.answer_report, name='answer_report'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path(r'register/', views.register, name='register'),
    path(r'user_info/', views.user_info, name='user_info'),
    path(r'user_info_edit/', views.myself_edit, name='user_info_edit'),
    path(r'upload_image/', views.my_image, name='upload_image'),
    path(r'others_info/<int:id>/', views.others_info, name='others_info'),
    path(r'follow_on/<int:id>/', views.follow_on, name='follow_on'),
    path(r'follow_cancel/<int:id>/', views.follow_cancel, name='follow_cancel'),
    path(r'user_follow/', views.user_follow, name='user_follow'),
    path(r'user_fan/', views.user_fan, name='user_fan'),
    path(r'my_collect/', views.my_collect, name='my_collect'),
]

templates/article_list.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}
{% block title %}
    首页
{% endblock %}

<div class="body">
    {% block body %}

        <style>
            .body {
                margin: 0 auto;

            }
        </style>
    {% endblock %}
</div>
{#在{% block main %}的这个标签外面加一层<div class="main"></div>然后修改.main的css样式即可#}
<div class="main">
    {% block main %}
        <div class="row">
            <form method="get" action="{% url 'article:article_search' %}" style="width:750px;">
                {% csrf_token %}
                <div class="input-group">
                    <div class="control">
                        <input style="width: 180px;" type="search" name="search" class="form-control"
                               placeholder="搜索博客(标题或内容)">
                        <button class="btn btn-default" type="submit">搜索</button>
                    </div>
                    <div class="btn-info">
                        <a href="{% url 'article:article_post' %}">
                            <button  class="btn btn-info" type="button">写博客</button>
                        </a>
                    </div>

                </div><!-- /input-group -->

            </form>

        </div><!-- /.row -->
        <ul class="question-list-group">
            {% for article in articles %}
                <li>
                    <div class="question-group">
                        <p class="question-title">
                            <a href="{% url 'article:article_detail' article.id %}">{{ article.title }}</a>
                        </p>
                        <p class="question-content">{{ article.content }}</p>
                        <div class="question-info">
                            <span class="question-author">
                                博主：<a
                                    href="{% url 'users:others_info' article.author.id %}">{{ article.author.username }}</a>
                            </span>
                            <span class="question-time">创作时间：{{ article.created }}</span>
                            <span>
                                <small class="col align-self-end" style="color: gray;">
                                    浏览: {{ article.total_views }}
                                </small>
                            </span>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
        <div>
            <h1 style="text-align: center">最热文章排行榜</h1>
            {% for article_view in articles_views %}
                {% if article_view.total_views != 0 %}

                    <div class="question-group">
                        <p class="question-title">
                            <a href="{% url 'article:article_detail' article_view.id %}">{{ article_view.title }}</a>
                        </p>
                        <p class="question-content">{{ article_view.content }}</p>
                        <div class="question-info">
                            <span class="question-author">
                                博主：<a
                                    href="{% url 'users:others_info' article_view.author.id %}">{{ article_view.author.username }}</a>
                            </span>
                            <span class="question-time">创作时间：{{ article_view.created }}</span>
                            <span>
                                <small class="col align-self-end" style="color: gray;">
                                    浏览: {{ article_view.total_views }}
                                </small>
                            </span>
                        </div>
                    </div>


                {% endif %}
            {% empty %}
                还没有人访问过博客！
            {% endfor %}
        </div>

        <style>
            ul {
                list-style: none;
                padding-left: 0;
            }

            ul li {
                border-bottom: 1px solid #eee;
                overflow: hidden;
                /*padding: 15px 0;*/
            }

            .main {
                background: #fff;
                width: 750px;
                margin: 0 auto;
                overflow: hidden;
                padding: 10px;
            }

            .question-group {
                float: left;
                width: 660px;
                margin-left: 10px;
            }

            .question-title a {
                color: #259;
                font-weight: 900;
            }

            .question-info {
                text-align: right;
            }

            .question-author {
                margin-right: 20px;
            }


            .control {
                margin-left: 20px;
                width: 260px;
                float: left;
            }

            .btn-info {
                float: right;
            }

            .input-group {
                width: 100%;
                margin-bottom: 10px;
            }
        </style>
    {% endblock %}
</div>

templates/base.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    {% block head %}{% endblock %}

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="navbar-static-top.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'base' %}">ACV博客系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                {#                class=active表示将此栏默认选中#}
                <li class="active"><a href="{% url 'base' %}">博客</a></li>
                <li><a href="{% url 'question:question_list' %}">问答</a></li>
                {#                <li class="dropdown">#}
                {#                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"#}
                {#                       aria-expanded="false"> <span class="caret"></span></a>#}
                {#                    <ul class="dropdown-menu">#}
                {#                        <li><a href="{% url 'article:article_post' %}">发表博客</a></li>#}
                {#                        <li><a href="#">发布问答</a></li>#}
                {#                    </ul>#}
                {#                </li>#}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    {% if user.is_authenticated %}
                        <a href="{% url 'users:user_info' %}">{{ request.user.username }}</a>
                    {% else %}
                        <a href="{% url 'login' %}">登录</a>
                    {% endif %}
                </li>
                <li>
                    {% if user.is_authenticated %}
                        <a href=" {% url 'logout' %} ">注销</a>
                    {% else %}
                        <a href="{% url 'users:register' %}">注册</a>
                    {% endif %}
                </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="body">
    {% block body %}

    {% endblock %}
</div>
<div class="main">
    {% block main %}

    {% endblock %}
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
<style>


    body {
        background: #E6E6E6;

    }

</style>
</html>

templates/imagecrop.html
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/imagecrop.css' %}">
<div class="container">
    <div class="imageBox">
        <div class="thumbBox"></div>
        <div class="spinner" style="display: none"></div>
    </div>

    <div class="action">
        <!-- <input type="file" id="file" style=" width: 200px">-->
        <div class="new-contentarea tc">
            <a href="javascript:void(0)" class="upload-img">
                <label for="upload-file">请先选择图片...</label>
            </a>
            <input type="file" class="" name="upload-file" id="upload-file"/>
        </div>
        <input type="button" id="btnCrop" class="Btnsty_peyton" value="OK"><!--注意这行代码，添加了 id="btnCrop" -->
        <input type="button" id="btnZoomIn" class="Btnsty_peyton" value="+">
        <input type="button" id="btnZoomOut" class="Btnsty_peyton" value="-">
    </div>
    <div class="cropped"></div>
</div>

<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/cropbox-min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/csrf.js' %}"></script>
<script type="text/javascript">
    $(window).load(function () {
        var options =
            {
                thumbBox: '.thumbBox',
                spinner: '.spinner',
                imgSrc: ''
            }
        var cropper = $('.imageBox').cropbox(options);
        var img = "";
        $('#upload-file').on('change', function () {
            var reader = new FileReader();
            reader.onload = function (e) {
                options.imgSrc = e.target.result;
                cropper = $('.imageBox').cropbox(options);
                getImg();
            }
            reader.readAsDataURL(this.files[0]);
            this.files = [];
        })
        $('#btnCrop').on('click', function () {
            //alert("图片上传喽");
            $.ajax({
                url: '{% url "users:upload_image" %}',
                type: 'POST',
                data: {"img": img},
                success: function (e) {
                    //location.href= "{% url 'users:user_info' %}"
                    if (e == "1") {
                        parent.location.reload();
                    } else {
                        alert("图片上传失败，请重试！.")
                    }
                },
            })
        })

        function getImg() {
            img = cropper.getDataURL();
            $('.cropped').html('');
            $('.cropped').append('<img src="' + img + '" align="absmiddle" style="width:180px; margin-top:4px; border-radius:180px; box-shadow:0px 0px 12px #7E7E7E;"> <p>180px*180px</p>');
            $('.cropped').append('<img src="' + img + '" align="absmiddle" style="width:128px; margin-top:4px; border-radius:128px; box-shadow:0px 0px 12px #7E7E7E;"> <p>128px*128px</p>');
            $('.cropped').append('<img src="' + img + '" align="absmiddle" style="width:64px; margin-top:4px; border-radius:64px; box-shadow:0px 0px 12px #7E7E7E;" > <p>64px*64px</p>');
        }

        $(".imageBox").on("mouseup", function () {
            getImg();
        });
        $('#btnZoomIn').on('click', function () {
            cropper.zoomIn();
        })
        $('#btnZoomOut').on('click', function () {
            cropper.zoomOut();
        })
    });
</script>

templates/index.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>首页</title>
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div>
            <h1 class="logo"><a href="{% url 'index' %}">Django Auth Example</a></h1>
            {#            当用户已经登录时返回 True，否则返回 False#}
            {% if user.is_authenticated %}
                <p>你已登录，欢迎你：<a href="#">{{ user.username }}</a></p>
                <button class="btn btn-default">
                    <a href="{% url 'logout' %}?next={{ request.path }}">注销登录</a>
                </button>
                <button class="btn btn-default">
                    <a href="{% url 'password_change' %}?next={{ request.path }}">修改密码</a>
                </button>
            {% else %}
                <p>你还没有登录，请
                    <button class="btn btn-default"><a href="{% url 'login' %}?next={{ request.path }}">登录</a></button>
                    或者
                    <button class="btn btn-default"><a href="{% url 'users:register' %}">注册</a></button>
                </p>
            {% endif %}
        </div>
    </div>
</div>
</body>
</html>

templates/my_collect.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}
{% block title %}
    我的收藏
{% endblock %}
{% load staticfiles %}
{#在{% block main %}的这个标签外面加一层<div class="main"></div>然后修改.main的css样式即可#}
<div class="main">
    {% block main %}
        <ul class="question-list-group">
            <h1 style="text-align: center">我收藏的博客</h1>
            {% for article in articles %}
                <li>
                    <div class="question-group">
                        <p class="question-title">
                            <a href="{% url 'article:article_detail' article.id %}">{{ article.title }}</a>
                        </p>
                        <p class="question-content">{{ article.content }}</p>
                        <div class="question-info">
                            <span class="question-time">创作时间：{{ article.created }}</span>
                        </div>
                    </div>
                </li>
            {% empty %}
                <div class="question-group">
                    您没有收藏的博客！
                </div>
                <br>
            {% endfor %}
            <h1 style="text-align: center">我收藏的问答</h1>
            {% for question in questions %}
                <li>
                    <div class="question-group">
                        <p class="question-title">
                            <a href="{% url 'question:question_detail' question.id %}">{{ question.title }}</a>
                        </p>
                        <p class="question-content">{{ question.content }}</p>
                        <div class="question-info">
                            <span class="question-author">
                                提问者:<a
                                    href="{% url 'users:others_info' question.author.id %}">{{ question.author.username }} </a>
                            </span>
                            <span>赏金：{{ question.integral }}积分</span>
                            <span class="question-time">提问时间:{{ question.created }}</span>
                        </div>
                    </div>
                </li>
            {% empty %}
                <div class="question-group">
                    您没有收藏的问答！
                </div>
                <br>
            {% endfor %}
        </ul>

        <style>
            ul {
                list-style: none;
                padding-left: 0;
            }

            ul li {
                border-bottom: 1px solid #eee;
                overflow: hidden;
                /*padding: 15px 0;*/
            }

            .main {
                background: #fff;
                width: 750px;
                margin: 0 auto;
                overflow: hidden;
                padding: 10px;
            }

            .question-group {
                float: left;
                width: 660px;
                margin-left: 10px;
            }

            .question-title a {
                color: #259;
                font-weight: 900;
            }

            .question-info {
                text-align: right;
            }

            .question-author {
                margin-right: 20px;
            }
        </style>

    {% endblock %}
</div>

templates/others_info.html
{% extends "base.html" %}
{% block title %}用户信息{% endblock %}
{% load staticfiles %}
{% block head %}

{% endblock %}
{% block body %}

{% endblock %}
<div class="main">
    {% block main %}
        <div class="col-md-2">
            <div class="bg-info">
                <div class="text-center" style="margin-top: 5px;">
                    <p><a href="{% url 'article:article_othersblog' user.id %}">TA的博客</a></p>
                </div>
                <div class="text-center" style="margin-top: 5px;">
                    <p><a href="{% url 'question:question_othersquestion' user.id %}">TA的问答</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-10">
            <div class="row text-center vertical-middle-sm">
                <h1 style="text-align: center;">博主信息</h1>
                {#                如果user.fan_user中包含当前用户即USER，则显示取消关注，否则显示关注博主#}
                {#                {% if f.follow == user and f.fan == follow %}#}
                {#                    <a href="#" onclick="follow_cancel()">取消关注</a>#}
                {#                {% else %}#}
                {#                    <a href="#" onclick="follow_on()">关注博主</a>#}
                {#                {% endif %}#}
                {% if f.count != 0 %}
                    <a href="#" onclick="follow_cancel()">取消关注</a>
                {% else %}
                    <a href="#" onclick="follow_on()">关注博主</a>
                {% endif %}


                <div class="row">
                    <div class="col-md-5">
                        <div class="row">
                            <div class="col-md-5 text-right"><span>昵称:</span></div>
                            <div class="col-md-7 text-left">{{ user.nickname }}</div>
                        </div>
                        <div class="row">
                            <div class="col-md-5 text-right"><span>毕业学校:</span></div>
                            <div class="col-md-7 text-left">{{ user.school }}</div>
                        </div>
                        <div class="row">
                            <div class="col-md-5 text-right"><span>职业:</span></div>
                            <div class="col-md-7 text-left">{{ user.profession }}</div>
                        </div>
                        <div class="row">
                            <div class="col-md-5 text-right"><span>地址:</span></div>
                            <div class="col-md-7 text-left">{{ user.address }}</div>
                        </div>
                        <div class="row">
                            <div class="col-md-5 text-right"><span>个人介绍:</span></div>
                            <div class="col-md-7 text-left">{{ user.aboutme }}</div>
                        </div>
                    </div>
                    <div style="margin-right:100px">

                        {% if user.photo %}
                            <img src="{{ user.photo | striptags }}" class="img-circle" id="my_photo" width="120px"
                                 name="user_face">
                        {% else %}
                            <img name="user_face" src="{% static 'images/user.jpg' %}" class="img-circle" id="my_photo"
                                 width="120px">
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>

        <script src='{% static "js/jquery-1.11.1.min.js" %}'></script>
        <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
        <script>
            // 关注博主的函数
            function follow_on() {
                // 调用layer弹窗组件
                layer.open({
                    // 弹窗标题
                    title: "关注",
                    // 正文
                    content: "确定要关注这个博主吗？",
                    // 点击确定按钮后调用的回调函数
                    yes: function (index, layero) {
                        // 指定应当前往的 url
                        location.href = '{% url "users:follow_on" user.id  %}'
                    },
                })
            }
        </script>
        <script>
            // 取消关注博主的函数
            function follow_cancel() {
                // 调用layer弹窗组件
                layer.open({
                    // 弹窗标题
                    title: "取消关注",
                    // 正文
                    content: "确定要取消关注这个博主吗？",
                    // 点击确定按钮后调用的回调函数
                    yes: function (index, layero) {
                        // 指定应当前往的 url
                        location.href = '{% url "users:follow_cancel" user.id  %}'
                    },
                    cancel: function () {
                        //右上角关闭回调
                    }
                })
            }
        </script>
        <style>
            .main {
                background: #fff;
                width: 750px;
                margin: 0 auto;
                overflow: hidden;
                padding: 10px;
            }
        </style>

    {% endblock %}

</div>

templates/users_info.html
{% extends "base.html" %}
{% block title %}用户信息{% endblock %}
{% load staticfiles %}
{% block body %}

{% endblock %}
<div class="main">
    {% block main %}
        <div class="col-md-2">
            <div class="bg-info">
                <div class="text-center" style="margin-top: 5px;">
                    <p><a href="{% url 'article:article_myblog' %}">我的博客</a></p>
                </div>
                <div class="text-center" style="margin-top: 5px;">
                    <p><a href="{% url 'question:question_myquestion' %}">我的问答</a></p>
                </div>
                <div class="text-center" style="margin-top: 5px;">
                    <p><a href="{% url 'users:user_follow' %}">我的关注</a></p>
                </div>
                <div class="text-center" style="margin-top: 5px;">
                    <p><a href="{% url 'users:user_fan' %}">我的粉丝</a></p>
                </div>
                <div class="text-center" style="margin-top: 5px;">
                    <p><a href="{% url 'users:my_collect' %}">我的收藏</a></p>
                </div>
                <div class="text-center" style="margin-top: 5px;">
                    <p><a href="{% url 'password_change' %}">修改密码</a></p>
                </div>
                <div class="text-center" style="margin-top: 5px;">
                    <p><a href="{% url 'users:user_info_edit' %}">修改个人信息</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-10">
            <div class="row text-center vertical-middle-sm">
                <h1 style="text-align: center;">我的信息</h1>
                <div class="row">
                    <div class="col-md-5">
                        <div class="row">
                            <div class="col-md-5 text-right"><span>用户名:</span></div>
                            <div class="col-md-7 text-left">{{ user.username }}</div>
                        </div>
                        <div class="row">
                            <div class="col-md-5 text-right"><span>邮箱:</span></div>
                            <div class="col-md-7 text-left">{{ user.email }}</div>
                        </div>
                        <div class="row">
                            <div class="col-md-5 text-right"><span>毕业学校:</span></div>
                            <div class="col-md-7 text-left">{{ user.school }}</div>
                        </div>
                        <div class="row">
                            <div class="col-md-5 text-right"><span>昵称:</span></div>
                            <div class="col-md-7 text-left">{{ user.nickname }}</div>
                        </div>
                        <div class="row">
                            <div class="col-md-5 text-right"><span>职业:</span></div>
                            <div class="col-md-7 text-left">{{ user.profession }}</div>
                        </div>
                        <div class="row">
                            <div class="col-md-5 text-right"><span>地址:</span></div>
                            <div class="col-md-7 text-left">{{ user.address }}</div>
                        </div>
                        <div class="row">
                            <div class="col-md-5 text-right"><span>个人介绍:</span></div>
                            <div class="col-md-7 text-left">{{ user.aboutme }}</div>
                        </div>
                    </div>
                    <div style="margin-right:100px">

                        {% if user.photo %}
                            <img src="{{ user.photo | striptags }}" class="img-circle" id="my_photo" width="120px"
                                 name="user_face">
                        {% else %}
                            <img name="user_face" src="{% static 'images/user.jpg' %}" class="img-circle" id="my_photo"
                                 width="120px">
                        {% endif %}
                        <div style="margin-right:3px">
                            {#                    <a href="{% url 'users:upload_image' %}">#}
                            <button class="btn btn-primary btn-lg" id="upload_image" onclick="upload_image_layer()">
                                上传头像
                            </button>
                            {#                    </a>#}
                        </div>
                    </div>
                </div>
            </div>


            <script type="text/javascript" src='{% static "js/jquery-1.11.1.min.js" %}'></script>
            <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
            <script>
                function upload_image_layer() {
                    layer.open({
                        title: "上传头像",
                        area: ['600px', '550px'],
                        type: 2,
                        content: "{% url 'users:upload_image' %}",
                    });
                }
            </script>

        </div>
        <style>
            .main {
                background: #fff;
                width: 750px;
                margin: 0 auto;
                overflow: hidden;
                padding: 10px;
            }
        </style>

    {% endblock %}
</div>