article/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'article'  # 一定要写这一行，否则html中会报错 'article' is not a registered namespace

urlpatterns = [
    path(r'article_post/', views.article_post, name='article_post'),
    path(r'article_list/', views.article_list, name='article_list'),
    path(r'article_detail/<int:id>/', views.article_detail, name='article_detail'),
    path(r'like_article/', views.like_article, name='like_article'),
    path(r'article_search/', views.article_search, name='article_search'),
    path(r'article_myblog/', views.article_myblog, name='article_myblog'),
    path(r'article_mysearch/', views.article_mysearch, name='article_mysearch'),
    path(r'article_delete/<int:id>/', views.article_delete, name='article_delete'),
    path(r'article_collect/<int:id>/', views.article_collect, name='article_collect'),
    path(r'article_collect_cancel/<int:id>/', views.article_collect_cancel, name='article_collect_cancel'),
    path(r'article_change/<int:id>/', views.article_change, name='article_change'),
    path(r'article_othersblog/<int:id>/', views.article_othersblog, name='article_othersblog'),
    path(r'article_othersearch/<int:id>/', views.article_othersearch, name='article_othersearch'),
    path(r'article_report/<int:id>/', views.article_report, name='article_report'),
    path(r'comment_report/<int:id>/', views.comment_report, name='comment_report'),
]

django_auth_example/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'users/', include('users.urls')),
    path(r'users/', include('django.contrib.auth.urls')),
    path(r'$/', views.index, name='base'),
    path(r'article/', include('article.urls')),
    path(r'question/', include('question.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path(r'register/', views.register, name='register'),
    path(r'user_info/', views.user_info, name='user_info'),
    path(r'user_info_edit/', views.myself_edit, name='user_info_edit'),
    path(r'upload_image/', views.my_image, name='upload_image'),
    path(r'others_info/<int:id>/', views.others_info, name='others_info'),
    path(r'follow_on/<int:id>/', views.follow_on, name='follow_on'),
    path(r'follow_cancel/<int:id>/', views.follow_cancel, name='follow_cancel'),
    path(r'user_follow/', views.user_follow, name='user_follow'),
    path(r'user_fan/', views.user_fan, name='user_fan'),
    path(r'my_collect/', views.my_collect, name='my_collect'),
]

article/models.py
from django.db import models

# Create your models here.

from django.db import models
from users.models import User
from django.utils import timezone
from django.urls import reverse


class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="article", null=True)
    title = models.CharField(max_length=200)
    content = models.TextField(null=True)
    created = models.DateTimeField(default=timezone.now, null=True)
    updated = models.DateTimeField(auto_now=True, null=True)
    users_like = models.ManyToManyField(User, related_name="articles_like", blank=True)
    collect_user = models.ManyToManyField(User, related_name="collect_user", blank=True)
    total_views = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ("-updated",)

    # 对数据库中的这两个字段建立索引，以后就可以通过每篇文章的id和slug来获取该文章对象了，
    # 这样建立索引以后，能提高读取文章对象的速度。
    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="comments")
    commentator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="commentator", null=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return "{0} 在 {1}博客中评论了".format(self.commentator.username, self.article)


class Report_Article(models.Model):
    reporter = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reporter_article")
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="reported_article")
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{0} 举报了 {1}博客，原因是：{2}.时间是{3}".format(self.reporter.username, self.article.title, self.content,
                                                     self.created)


class Report_Commit(models.Model):
    reporter = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reporter_commit")
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name="reported_commit")
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{0} 举报了 {1}用户在标题为{2}的博客下的{3}的评论，原因是：{4}。时间是{5}".format(self.reporter.username,
                                                                       self.comment.commentator.username,
                                                                       self.comment.article.title, self.comment.body,
                                                                       self.content, self.created)

article/forms.py
from django import forms
from .models import Article, Comment


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ("title", "content")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("commentator", "body",)

article/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from .forms import ArticlePostForm, CommentForm
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from .models import Article, Comment, Report_Article, Report_Commit
from django.views.decorators.http import require_POST
from django.utils import timezone
from users.models import User
from django.db.models import Q


def article_list(request):
    articles = Article.objects.all()
    articles_views = Article.objects.all().order_by('-total_views')
    return render(request, 'article_list.html', {'articles': articles, 'articles_views': articles_views})


@login_required(login_url='/users/login/')
@csrf_exempt
def article_post(request):
    user = User.objects.get(username=request.user.username)
    if request.method == "POST":
        article_post_form = ArticlePostForm(request.POST)
        if article_post_form.is_valid():
            # cd = article_post_form.cleaned_data
            try:
                new_article = Article()
                # new_article=Article.objects.create_article(title,content)
                # new_article = article_post_form.save(commit=False)
                author = user
                new_article.author = author
                title = request.POST.get('title', None)
                content = request.POST.get('content', None)
                new_article.title = title
                new_article.content = content
                new_article.save()
                return redirect('article:article_list')
            except:
                return HttpResponse("2")
    else:
        article_post_form = ArticlePostForm()

        return render(request, "article/article.html",
                      {"article_post_form": article_post_form})


@login_required(login_url='/users/login/')
def article_detail(request, id):
    article = Article.objects.get(id=id)
    user = User.objects.get(username=request.user.username)
    a = Article.objects.filter(id=id, collect_user=user)
    article.total_views += 1
    # 只修改article的total_views属性
    article.save(update_fields=['total_views'])

    if request.method == "POST":
        comment = request.POST.get('comment', None)
        # article_id = request.POST.get('article_id', None)
        new_comment = Comment()
        new_comment.article = article
        new_comment.body = comment
        new_comment.commentator = user
        new_comment.save()
    else:
        pass
    return render(request, 'article/article_detail.html',
                  {'article': article, 'user': user, 'a': a})


@csrf_exempt
@require_POST
@login_required(login_url='/users/login/')
def like_article(request):
    article_id = request.POST.get("id")
    action = request.POST.get("action")
    if article_id and action:
        try:
            article = Article.objects.get(id=article_id)
            if action == "like":
                article.users_like.add(request.user)
                return HttpResponse("1")
            else:
                article.users_like.remove(request.user)
                return HttpResponse("2")
        except:
            return HttpResponse("no")


def article_search(request):
    search = request.GET.get('search', None)
    error_msg = ''
    if search:
        articles = Article.objects.filter(Q(title__icontains=search) | Q(content__icontains=search))
    else:
        # 将 search 参数重置为空,否则search则为None
        search = ''
        articles = Article.objects.all()
    return render(request, 'article/article_search.html', {'articles': articles})


@login_required(login_url='/users/login/')
def article_myblog(request):
    user = User.objects.get(username=request.user.username)
    articles = Article.objects.filter(author=user)
    return render(request, 'article/article_myblog.html', {'articles': articles})


@login_required(login_url='/users/login/')
def article_mysearch(request):
    search = request.GET.get('search', None)
    user = User.objects.get(username=request.user.username)
    error_msg = ''
    if search:
        articles = Article.objects.filter((Q(title__icontains=search) | Q(content__icontains=search)), author=user)
    else:
        # 将 search 参数重置为空,否则search则为None
        search = ''
        articles = Article.objects.filter(author=user)
    return render(request, 'article/article_mysearch.html', {'articles': articles})


@login_required(login_url='/users/login/')
def article_delete(request, id):
    # 根据 id 获取需要删除的文章
    article = Article.objects.get(id=id)
    # 调用.delete()方法删除文章
    article.delete()
    # 完成删除后返回文章列表
    return redirect("article:article_list")


@login_required(login_url='/users/login/')
@csrf_exempt
def article_change(request, id):
    user = User.objects.get(username=request.user.username)
    article = Article.objects.get(id=id)
    if request.method == "POST":
        title = request.POST.get('title', None)
        content = request.POST.get('content', None)
        article.title = title
        article.content = content
        article.save()
        return redirect('article:article_detail', id)
    else:
        return render(request, "article/article_change.html", {"article": article})


def article_othersblog(request, id):
    user = User.objects.get(id=id)
    articles = Article.objects.filter(author=user)
    return render(request, 'article/article_othersblog.html', {'articles': articles, 'user': user})


def article_othersearch(request, id):
    search = request.GET.get('search', None)
    user = User.objects.get(id=id)
    error_msg = ''
    if search:
        articles = Article.objects.filter((Q(title__icontains=search) | Q(content__icontains=search)), author=user)
    else:
        # 将 search 参数重置为空,否则search则为None
        search = ''
        articles = Article.objects.filter(author=user)
    return render(request, 'article/article_othersearch.html', {'articles': articles, 'user': user})


@login_required(login_url='/users/login/')
def article_collect(request, id):
    # 根据 id 获取需要收藏的文章
    article = Article.objects.get(id=id)
    user = User.objects.get(username=request.user.username)
    # 多对多关系赋值时用add而不是=
    article.collect_user.add(user)
    article.save()
    # 完成收藏后返回文章详情
    a = Article.objects.filter(id=id, collect_user=user)
    return render(request, 'article/article_detail.html', {'article': article, 'user': user, 'a': a})


@login_required(login_url='/users/login/')
def article_collect_cancel(request, id):
    # 根据 id 获取需要取消收藏的文章
    article = Article.objects.get(id=id)
    user = User.objects.get(username=request.user.username)
    # 多对多关系消除时用remove而不是赋值为None或者remove（）
    article.collect_user.remove(user)
    article.save()
    a = Article.objects.filter(id=id, collect_user=user)
    # 完成收藏后返回文章详情
    return render(request, 'article/article_detail.html', {'article': article, 'user': user, 'a': a})


@login_required(login_url='/users/login/')
@csrf_exempt
def article_report(request, id):
    user = User.objects.get(username=request.user.username)
    article = Article.objects.get(id=id)
    if request.method == "POST":
        content = request.POST.get('content', None)
        ra = Report_Article()
        ra.reporter = user
        ra.article = article
        ra.content = content
        ra.save()
        return render(request, 'report_success.html')
    else:
        return render(request, 'article/article_report.html', {'article': article})


@login_required(login_url='/users/login/')
@csrf_exempt
def comment_report(request, id):
    # 传进来的id是评论的id
    comment = Comment.objects.get(id=id)
    user = User.objects.get(username=request.user.username)
    if request.method == "POST":
        content = request.POST.get('content', None)
        ra = Report_Commit()
        ra.reporter = user
        ra.comment = comment
        ra.content = content
        ra.save()
        return render(request, 'report_success.html')
    else:
        return render(request, 'article/comment_report.html', {'comment': comment})

templates/article/article.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}发表博客{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
{% endblock %}

<div class="main">
    {% block main %}
        <h3 class="page-title">发表博客</h3>
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-container">
                <div class="form-group">
                    <input id="id_title" class="form-control" type="text" placeholder="请输入标题" name="title">
                </div>
                <div id="editormd" class="col-md-10 text-left">
                    <textarea name="content" style="display:none;"></textarea>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary" onclick="publish_article()">立即发布</button>
                </div>
            </div>
        </form>
        <style>
            .form-container {
                width: 800px;
                margin: 0 auto;
                text-align: right;
            }

            .page-title {
                text-align: center;
            }

            body {
                background: #E6E6E6;
            }

            .main {
                background: #fff;
                width: 1000px;
                margin: 0 auto;
                overflow: hidden;
                padding: 10px;
            }
        </style>

        <script type="text/javascript" src='{% static "js/jquery-1.11.1.min.js" %}'></script>
        <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
        <script type="text/javascript">
            function publish_article() {
                {#var title = $("#id_title").val();#}
                {#var body = $("#id_body").val();#}
                {#var article_tags = [];#}
                {#$.each($("input[name='article_tag']:checked"), function () {#}
                {#    article_tags.push($(this).val());});#}
                {#"tags": JSON.stringify(article_tags)#}
                $.ajax({
                    url: "{% url 'article:article_post' %}",
                    dataType:"text",
                    type: "GET",
                    {#data: {"title": title, },#}
                    success: function (e) {
                        if (e == "1") {
                            layer.msg("发布成功！", {
                                time: 700,
                                end: function () {
                                    location.href = "{% url 'article:article_list' %}";//修改后：文章发布成功后跳转到文章列表
                                }
                            });
                        } else if (e == "2") {
                            layer.msg("发布失败，请重试！", {
                                time: 700,
                                end: function () {
                                }
                            });
                        }
                    },
                });
            }
        </script>
        <script type="text/javascript" src='{% static "editor/editormd.min.js" %}'></script>
        <script type="text/javascript">
            $(function () {
                var editor = editormd("editormd", {
                    width: "100%",
                    height: 640,
                    syncScrolling: "single",
                    path: "{% static 'editor/lib/' %}"
                });
            });
        </script>
    {% endblock %}
</div>

templates/article/article_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}文章详情{% endblock %}

{% block head %}

{% endblock %}

<div class="main">
    {% block main %}
        {% with total_likes=article.users_like.count users_like=article.users_like.all %}
            <h3 class="page-title">{{ article.title }}</h3>
            <p class="question-info">
                <span class="span">博主：
                    {% if article.author.photo %}
                        <a href="{% url 'users:others_info' article.author.id %}">
                        <img src="{{ article.author.photo | striptags }}" class="img-circle" id="my_photo" width="20px"
                             name="user_face">
                        </a>
                    {% else %}
                        <a href="{% url 'users:others_info' article.author.id %}">
                        <img name="user_face" src="{% static 'images/user.jpg' %}" class="img-circle" id="my_photo"
                             width="20px">
                        </a>
                    {% endif %}
                    <a href="{% url 'users:others_info' article.author.id %}">{{ article.author.username }}</a>
                </span>
                <span>发表时间:{{ article.created }}</span>
                <span style="margin-left:20px"
                      class="glyphicon glyphicon-thumbs-up">{{ total_likes }}like{{ total_likes|pluralize }}</span>
                {% if article.author.username != user.username %}
                    <span>
                    浏览量：{{ article.total_views }}
                    </span>
                    {% if a.exists %}
                        <a href="#" onclick="confirm_collect_cancel()">取消收藏</a>
                    {% else %}
                        <a href="#" onclick="confirm_collect()">收藏博客</a>
                    {% endif %}
                {% endif %}
                {% if article.author.username == user.username %}
                    <a href="#" onclick="confirm_delete()">删除博客</a>
                {% endif %}
                {% if article.author.username == user.username %}
                    <a href="{% url 'article:article_change' article.id %}">修改博客</a>
                {% endif %}
            </p>
            <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}"/>
            <div id='editormd-view'>
        <textarea id="append-test" style="display:none;" class="question-content">
{{ article.content }}
        </textarea>
            </div>
            <div>
                <p class="text-center">
                    <a onclick="like_article({{ article.id }}, 'like')" href="#">
                        <span class="glyphicon glyphicon-thumbs-up">like</span>
                    </a>
                    <a onclick="like_article({{ article.id }}, 'unlike')" href="#">
                        <span style="margin-left: 15px;" class="glyphicon glyphicon-thumbs-down">unlike</span>
                    </a>
                </p>
            </div>
            <div>
                <p class="text-center"><strong>点赞本文的读者</strong></p>
                {% for user in article.users_like.all %}
                    <p class="text-center">
                        {% if article.author.photo %}
                            <a href="{% url 'users:others_info' user.id %}">
                                <img src="{{ user.photo | striptags }}" class="img-circle" id="my_photo" width="25px"
                                     name="user_face">
                            </a>
                        {% else %}
                            <a href="{% url 'users:others_info' user.id %}">
                                <img name="user_face" src="{% static 'images/user.jpg' %}" class="img-circle"
                                     id="my_photo" width="25px">
                            </a>
                        {% endif %}
                        <a href="{% url 'users:others_info' user.id %}">{{ user.username }}</a>
                    </p>
                {% empty %}
                    <p class="text-center">还没有人对此文章表态</p>
                {% endfor %}
            </div>
            <h3><span class="glyphicon glyphicon-bullhorn"></span>本文有
                {{ article.comments.count }}
                条评论</h3>
            <div>
                <ul class="answer-list">
                    {% for comment in article.comments.all %}
                        <div class="user-info">
                            {#                    <img src="{{ url_for('static',filename='') }}"alt="" class="avatar">#}
                            <span class="username">
                                {% if comment.commentator.photo %}
                                    <a href="{% url 'users:others_info' comment.commentator.id %}">
                                <img src="{{ comment.commentator.photo | striptags }}" class="img-circle" id="my_photo"
                                     width="40px"
                                     name="user_face">
                            </a>
                                {% else %}
                                    <a href="{% url 'users:others_info' comment.commentator.id %}">
                                <img name="user_face" src="{% static 'images/user.jpg' %}" class="img-circle"
                                     id="my_photo"
                                     width="40px">
                            </a>
                                {% endif %}
                                <a href="{% url 'users:others_info' comment.commentator.id %}">{{ comment.commentator }}</a>
                            </span>
                            <span class="create-time">{{ comment.created }}</span>
                        </div>
                        <p class="answer-content">
                            {{ comment.body }}
                        </p>
                        <a href="{% url 'article:comment_report' comment.id %}" style="color:#BBBBBB;float:right">举报</a>
                        <hr>
                    {% empty %}
                        <div class="question-group">
                            还没有评论哦，快来占沙发吧！
                        </div>
                    {% endfor %}
                </ul>


                <form action="." method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <textarea type="text" name="comment" class="form-control" placeholder="请填写评论"></textarea>
                    </div>
                    <input type="hidden" name="article_id" value="{{ article.id }}">
                    <div class="form-group" style="text-align: right">
                        <button class="btn btn-primary">立即评论</button>
                    </div>
                </form>
                <a href="#" onclick="report_article()">举报</a>
            </div>



            <script src='{% static "js/jquery-1.11.1.min.js" %}'></script>
            <script src='{% static "editor/lib/marked.min.js" %}'></script>
            <script src='{% static "editor/lib/prettify.min.js" %}'></script>
            <script src='{% static "editor/lib/raphael.min.js" %}'></script>
            <script src='{% static "editor/lib/underscore.min.js" %}'></script>
            <script src='{% static "editor/lib/sequence-diagram.min.js" %}'></script>
            <script src='{% static "editor/lib/flowchart.min.js" %}'></script>
            <script src='{% static "editor/lib/jquery.flowchart.min.js" %}'></script>
            <script src='{% static "editor/editormd.js" %}'></script>
            <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
            <script type="text/javascript">
                $(function () {
                    editormd.markdownToHTML("editormd-view", {
                        htmlDecode: "style, script, iframe",
                        emoji: true,
                        taskList: true,
                        tex: true,
                        flowChart: true,
                        sequenceDiagram: true,
                    });
                });

                function like_article(id, action) {
                    $.ajax({
                        url: "{% url 'article:like_article' %}",
                        type: "POST",
                        data: {"id": id, "action": action},
                        success: function (e) {
                            if (e == "1") {
                                layer.msg("感谢点赞", {
                                    time: 700,
                                    end: function () {
                                        window.location.reload();
                                    }

                                });

                            } else {
                                layer.msg("我会继续努力", {
                                    time: 700,
                                    end: function () {
                                        window.location.reload();
                                    }

                                });
                            }
                        },
                    });
                }

            </script>
            <script>
                // 删除文章的函数
                function confirm_delete() {
                    // 调用layer弹窗组件
                    layer.open({
                        // 弹窗标题
                        title: "确认删除",
                        // 正文
                        content: "确认删除这篇博客吗？",
                        // 点击确定按钮后调用的回调函数
                        yes: function (index, layero) {
                            // 指定应当前往的 url
                            location.href = '{% url "article:article_delete" article.id %}'
                        },
                    })
                }
            </script>
            <script>
                // 收藏文章的函数
                function confirm_collect() {
                    // 调用layer弹窗组件
                    layer.open({
                        // 弹窗标题
                        title: "确认收藏",
                        // 正文
                        content: "确认收藏这篇博客吗？",
                        // 点击确定按钮后调用的回调函数
                        yes: function (index, layero) {
                            // 指定应当前往的 url
                            location.href = '{% url "article:article_collect" article.id %}'
                        },
                    })
                }
            </script>
            <script>
                // 收藏文章的函数
                function confirm_collect_cancel() {
                    // 调用layer弹窗组件
                    layer.open({
                        // 弹窗标题
                        title: "取消收藏",
                        // 正文
                        content: "确认取消收藏这篇博客吗？",
                        // 点击确定按钮后调用的回调函数
                        yes: function (index, layero) {
                            // 指定应当前往的 url
                            location.href = '{% url "article:article_collect_cancel" article.id %}'
                        },
                    })
                }
            </script>
            <script>
                // 举报博客的函数
                function report_article() {
                    // 调用layer弹窗组件
                    layer.open({
                        // 弹窗标题
                        title: "举报博客",
                        // 正文
                        content: "确认举报这篇博客吗？举报属实会有奖励，但举报若不属实则会有惩罚",
                        // 点击确定按钮后调用的回调函数
                        yes: function (index, layero) {
                            // 指定应当前往的 url
                            location.href = '{% url "article:article_report" article.id %}'
                        },
                    })
                }
            </script>


            <style>
                .main {
                    background: #fff;
                    width: 750px;
                    margin: 0 auto;
                    overflow: hidden;
                    padding: 10px;
                }

                .page-title {
                    text-align: center;
                    font-weight: 800;
                }

                .question-info {
                    text-align: center;
                    margin-top: 20px;

                }

                .question-content {
                    margin-left: 10px;
                }

                .span {
                    margin-right: 10px;
                }

                .form-control {
                    width: 650px;
                }

                .form-group {
                    margin-left: 10px;
                }

                .font-control {
                    margin-left: 10px;
                }

                .form-group {
                    margin-right: 48px;
                }

                .line-control {
                    line-height: 300%;
                }

                .answer-list li {
                    list-style: none;
                    border-bottom: 1px solid #eee;
                    padding-top: 10px;
                }

                .answer-list {
                    padding-left: 0;
                }

                .user-info {
                    font-size: 16px;
                    color: #9b9b9b;
                    line-height: 40px;
                }

                .user-info .username {
                    margin-left: 20px;
                }

                .user-info .create-time {
                    float: right;
                }

                .answer-content {
                    margin-left: 60px;
                    font-size: 20px;
                }
            </style>
        {% endwith %}
    {% endblock %}
</div>